package cn.lk.newsssm.dao;


import java.util.List;





import org.apache.ibatis.annotations.Param;

import cn.lk.newsssm.entity.Comment;
import cn.lk.newsssm.entity.News;

public interface CommentDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    int insertSelective(Comment record);

 

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    Comment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Comment record);

	List<Comment> getCommentsByNewsId(Integer id);

	int getCount(@Param("newsId") int newsId);

	List<Comment> list(@Param("id") int newsId,@Param("offset") int page, @Param("rows")int rows);

	void approve(@Param("id")int id,@Param("favour") int favour);

	void disapprove(@Param("id")int id,@Param("disfavour") int disfavour);
}